name: Deploy Pipeline

on:
  push:
    branches:
      - dev
      #- main
  #workflow_call: 
  workflow_dispatch:

jobs:
  deploy_dev:
    name: Deploy to Dev
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: dev
    secrets:
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      # REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      # REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      # REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }} 

      
  deploy_prod:
    name: Deploy to Prod
    if: github.ref == 'refs/heads/main'
    #needs: deploy_dev
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: prod
    secrets:
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      # REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      # REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      # REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}       

