name: Deploy Pipeline

on:
  push:
    branches:
      - dev
      #- main
  #workflow_call: 
  workflow_dispatch:

jobs:
  deploy_dev:
    name: Deploy to Dev
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: dev
    secrets:
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      
  deploy_prod:
    name: Deploy to Prod
    #needs: deploy_dev
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: prod
    secrets:
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
