name: environment-test
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Branch Name
        run: |
          echo "Host: $GITHUB_REF_NAME"

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3              

      - name: 'Setup Azure Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}        
