# main.yml
name: Test, lint, build, migrate database, and deploy

on:
  push:
    branches:
      - dev
      #- main
  #workflow_call: 
  workflow_dispatch:

jobs:

  dev-deployment:
    #needs: test-lint-build
    if: github.ref == 'refs/heads/dev'
    strategy:
      matrix:
        environment: ['dev']
    uses: ./.github/workflows/deploy2.yml

  prod-deployment:
    #needs: test-lint-build
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        environment: ['prod']
    uses: ./.github/workflows/deploy2.yml
