# main.yml
name: Test, lint, build, migrate database, and deploy

on:
  push:
    branches:
      - dev
      #- main
  workflow_call:
  workflow_dispatch:

jobs:

  dev-deployment:
    #needs: test-lint-build
    if: github.ref == 'refs/heads/dev'
    strategy:
      matrix:
        environment: ['dev']
    uses: Bharat-vyas1/environment-test/.github/workflows/deploy2.yml@391193a7679410c4925c7778e8ba9a2c811e2b8f

  prod-deployment:
    #needs: test-lint-build
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        environment: ['prod']
    uses: ./.github/workflows/deploy2.yml
