name: Deploy Template

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
    secrets:
      ENVIRONMENT:
        required: true
    #   REGISTRY_LOGIN_SERVER:
    #     required: true
    #   REGISTRY_USERNAME:
    #     required: true
    #   REGISTRY_PASSWORD:
    #     required: true                

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Dump Password
        run: |
          echo Environment is $ENVIRONMENT
          if [[ $ENVIRONMENT == *"prod"* ]]; then
            echo "This is the prod Environment!"
          else
            echo "This is NOT the prod Environment!"
          fi
        env:
          ENVIRONMENT: $ {{ secrets.ENVIRONMENT }}
        #PASSWORD: ${{ secrets.PASSWORD }}

 
      - name: Branch Name
        run: |
          echo "Host: $GITHUB_REF_NAME"      


      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Setup Azure Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}          
        env:
          ENVIRONMENT: $ {{ secrets.ENVIRONMENT }}
          REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}                     
